export const teluguMovies = [
  {
    id: 1,
    title: "RRR",
    year: 2022,
    director: "S. S. Rajamouli",
    description:
      "Epic historical fiction about two legendary revolutionaries and their journey away from home before they started fighting for their country.",
    detections: 1250,
    poster: "/images/rrr-film-poster.jpg",
  },
  {
    id: 2,
    title: "Baahubali: The Beginning",
    year: 2015,
    director: "S. S. Rajamouli",
    description:
      "In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.",
    detections: 980,
    poster: "/images/baahubali-beginning-poster.jpg",
  },
  {
    id: 3,
    title: "Baahubali 2: The Conclusion",
    year: 2017,
    director: "S. S. Rajamouli",
    description:
      "Amarendra Baahubali, the heir apparent to the throne of Mahishmati, finds his life and relationships endangered as his adoptive brother Bhallaladeva conspires to claim the throne.",
    detections: 1120,
    poster: "/images/baahubali-2-poster.jpg",
  },
  {
    id: 4,
    title: "Pushpa: The Rise",
    year: 2021,
    director: "Sukumar",
    description:
      "Violence erupts between red sandalwood smugglers and the police charged with bringing down their organization.",
    detections: 890,
    poster: "/images/pushpa2-film-poster.jpg",
  },
  {
    id: 5,
    title: "Eega",
    year: 2012,
    director: "S. S. Rajamouli",
    description:
      "Nani loves Bindu but is killed by a jealous Sudeep, who lusts after Bindu. Nani is reincarnated as a fly and decides to avenge his death.",
    detections: 420,
    poster: "/images/eega-poster.jpg",
  },
  {
    id: 6,
    title: "Arjun Reddy",
    year: 2017,
    director: "Sandeep Reddy Vanga",
    description:
      "Arjun Reddy, a short-tempered house surgeon, gets used to drugs and drinks when his girlfriend is forced to marry another person.",
    detections: 650,
    poster: "/images/arjun-reddy-poster.jpg",
  },
  {
    id: 7,
    title: "Ala Vaikunthapurramuloo",
    year: 2020,
    director: "Trivikram Srinivas",
    description:
      "After growing up enduring criticism from his father, a young man finds his world shaken upon learning that he was switched at birth with a millionaire's son.",
    detections: 720,
    poster: "/images/ala-vaikunthapuramlo-poster.jpeg",
  },
  {
    id: 8,
    title: "Attarintiki Daredi",
    year: 2013,
    director: "Trivikram Srinivas",
    description:
      "The scion of a powerful family is tasked with retrieving his estranged aunt, a former princess who was expelled from their homeland years ago.",
    detections: 540,
    poster: "/images/attarintiki-daredi-poster.webp",
  },
  {
    id: 11,
    title: "Srimanthudu",
    year: 2015,
    director: "Koratala Siva",
    description:
      "Harsha, a multi-millionaire guy who has everything but there is something else he's looking for and in the process he adopts a village to bring change in the people.",
    detections: 450,
    poster: "/images/srimanthudu-poster.jpg",
  },
  {
    id: 12,
    title: "Sarileru Neekevvaru",
    year: 2020,
    director: "Anil Ravipudi",
    description:
      "An army major goes undercover as a college student to protect his professor's daughter from mobsters.",
    detections: 380,
    poster: "/images/sarileru-neekevvaru-poster.webp",
  },
  {
    id: 13,
    title: "Julayi",
    year: 2012,
    director: "Trivikram Srinivas",
    description:
      "An intelligent young man and a cop trace a counterfeiting criminal with the help of a careless yet honest thief.",
    detections: 340,
    poster: "/images/julai-poster.jpg",
  },
  {
    id: 14,
    title: "Fidaa",
    year: 2017,
    director: "Sekhar Kammula",
    description: "A heart-warming romantic tale depicting traditional values and romance set against a rural backdrop.",
    detections: 420,
    poster: "/images/fidaa-poster.webp",
  },
  {
    id: 15,
    title: "Khaidi No. 150",
    year: 2017,
    director: "V. V. Vinayak",
    description:
      "A convict who plans to kill the corrupt industrialist who murdered his sister, adopts a new identity after escaping from prison.",
    detections: 390,
    poster: "/images/khaidi-150-poster.jpg",
  },
  {
    id: 16,
    title: "Temper",
    year: 2015,
    director: "Puri Jagannadh",
    description: "A corrupt police officer faces a moral dilemma when he crosses paths with a wealthy criminal.",
    detections: 360,
    poster: "/images/temper-poster.jpg",
  },
  {
    id: 17,
    title: "Janatha Garage",
    year: 2016,
    director: "Koratala Siva",
    description:
      "An environmental activist comes to a village to rescue his mentor, who is held captive by a powerful businessman.",
    detections: 480,
    poster: "/images/janatha-garage-poster.jpg",
  },
  {
    id: 18,
    title: "Bharat Ane Nenu",
    year: 2018,
    director: "Koratala Siva",
    description:
      "Bharat, a young graduate who becomes the Chief Minister of Andhra Pradesh, has to deal with the corrupt political system.",
    detections: 520,
    poster: "/images/bharat-ane-nenu-poster.jpg",
  },
  {
    id: 19,
    title: "Sye Raa Narasimha Reddy",
    year: 2019,
    director: "Surender Reddy",
    description:
      "A historical action epic about the freedom fighter Uyyalawada Narasimha Reddy who fought against the atrocities of East India Company.",
    detections: 440,
    poster: "/images/sye-raa-poster.jpg",
  },
  {
    id: 20,
    title: "Geetha Govindam",
    year: 2018,
    director: "Parasuram Petla",
    description:
      "An innocent young lecturer is misunderstood as a pervert and despised by a woman who co-incidentally turns out to be his brother-in-law's sister.",
    detections: 580,
    poster: "/images/geetha-govindam-poster.jpg",
  },
  {
    id: 21,
    title: "Pokiri",
    year: 2006,
    director: "Puri Jagannadh",
    description:
      "A hot-blooded but righteous man, Pandu, who was forced to become a rogue protects the people from mafia and corrupt politicians.",
    detections: 620,
    poster: "/images/pokiri-poster.jpg",
  },
  {
    id: 22,
    title: "Kick",
    year: 2009,
    director: "Surender Reddy",
    description: "A young man with a self-destructive attitude seeks excitement in all the wrong places.",
    detections: 290,
    poster: "/images/kick-poster.webp",
  },
  {
    id: 23,
    title: "Dookudu",
    year: 2011,
    director: "Srinu Vaitla",
    description: "A young police officer searches for his father's killers while trying to avenge his death.",
    detections: 470,
    poster: "/images/dookudu-poster.jpg",
  },
  {
    id: 24,
    title: "Mirchi",
    year: 2013,
    director: "Koratala Siva",
    description:
      "A man returns to his country in order to get his family's land back and falls in love with a village girl.",
    detections: 380,
    poster: "/images/mv5byjrkowyyzgqtoda5my00mgizlwe3mjytzmiznzk4nmrmyjuxxkeyxkfqcgc-40.jpg",
  },
  {
    id: 25,
    title: "Seethamma Vakitlo Sirimalle Chettu",
    year: 2013,
    director: "Srikanth Addala",
    description: "A family story between two brothers who goes through ups and downs in life.",
    detections: 310,
    poster: "/images/images-20-284-29.webp",
  },
  {
    id: 31,
    title: "Jersey",
    year: 2019,
    director: "Gowtam Tinnanuri",
    description:
      "A failed cricketer decides to revive his cricketing career in his late 30s despite everyone being skeptical.",
    detections: 460,
    poster: "/images/jersey-2019-poster.jpg",
  },
  {
    id: 35,
    title: "Bheemla Nayak",
    year: 2022,
    director: "Saagar K Chandra",
    description:
      "Things turn heated between a Sub-Inspector and a retired army man who refuses to bow to the former's authority.",
    detections: 370,
    poster: "/images/bheemla-nayak.jpg",
  },
  {
    id: 36,
    title: "KGF Chapter 2",
    year: 2022,
    director: "Prashanth Neel",
    description:
      "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes while the government sees him as a threat.",
    detections: 920,
    poster: "/images/images-20-285-29.webp",
  },
  {
    id: 37,
    title: "Sita Ramam",
    year: 2022,
    director: "Hanu Raghavapudi",
    description:
      "An orphan soldier, Lieutenant Ram's life changes after he receives letters from a girl named Sita during the Indo-Pak war.",
    detections: 540,
    poster: "/images/mv5bywe0ndninzetnthmmi00njzlltk3ndatyzizownmnwqyyti3xkeyxkfqcgc-40.jpg",
  },
  {
    id: 38,
    title: "Uppena",
    year: 2021,
    director: "Buchi Babu Sana",
    description:
      "A fisherman's son falls in love with a village head's daughter, but class barriers and a violent family stand in their way.",
    detections: 480,
    poster: "/images/images-20-286-29.webp",
  },
  {
    id: 40,
    title: "Krack",
    year: 2021,
    director: "Gopichand Malineni",
    description:
      "Krack is an action film which follows Veera Shankar, a hot headed police sergeant, who forms a vicious rivalry with notorious crime boss Katari Krishna.",
    detections: 330,
    poster: "/images/krack-movie-poster.jpeg",
  },
  {
    id: 41,
    title: "Akhanda",
    year: 2021,
    director: "Boyapati Srinu",
    description:
      "Akhanda is a powerful Aghora who challenges the evil industrialists who try to harm the people of his village.",
    detections: 450,
    poster: "/images/akhanda-movie-poster.jpeg",
  },
  {
    id: 43,
    title: "Jathi Ratnalu",
    year: 2021,
    director: "Anudeep K.V.",
    description:
      "Three youngsters in a small village try to find their way to the city but get into hilarious situations.",
    detections: 420,
    poster: "/images/jathiratnalu-movie-poster.webp",
  },
  {
    id: 44,
    title: "Maharshi",
    year: 2019,
    director: "Vamshi Paidipally",
    description: "A successful CEO faces a crisis and returns to his village to help farmers.",
    detections: 480,
    poster: "/images/maharshi-movie-poster.webp",
  },
  {
    id: 45,
    title: "Saaho",
    year: 2019,
    director: "Sujeeth",
    description:
      "An undercover agent and his mission to find the person who stole crores of money from India's most powerful man.",
    detections: 530,
    poster: "/images/saaho-movie-poster.jpg",
  },
  {
    id: 46,
    title: "Vinaya Vidheya Rama",
    year: 2019,
    director: "Boyapati Srinu",
    description:
      "When a heartless criminal mastermind threatens the safety of a young girl, an adopted righteous man must take action.",
    detections: 280,
    poster: "/images/dvv-movie-poster.jpg",
  },
  {
    id: 47,
    title: "F2 - Fun and Frustration",
    year: 2019,
    director: "Anil Ravipudi",
    description:
      "After Venky, Varun also gets married to frustration. They decide to commit suicide when they meet each other.",
    detections: 390,
    poster: "/images/f2-movie-poster.jpg",
  },
  {
    id: 48,
    title: "Chitralahari",
    year: 2019,
    director: "Kishore Tirumala",
    description: "A serial failure in life, Vijay, tries to bounce back and make it big in his life.",
    detections: 260,
    poster: "/images/chitralahari-movie-poster.webp",
  },
  {
    id: 49,
    title: "Dear Comrade",
    year: 2019,
    director: "Bharat Kamma",
    description:
      "A hot-blooded student union leader falls for a state-level cricketer but she wants to focus on her career.",
    detections: 350,
    poster: "/images/dear-comrade-movie-poster.jpg",
  },
  {
    id: 50,
    title: "Majili",
    year: 2019,
    director: "Shiva Nirvana",
    description:
      "A former cricketer struggling to make ends meet wants to fulfill his child's dream of getting a jersey.",
    detections: 410,
    poster: "/images/majili-new-poster.webp",
  },
]
